[package]
name = "edgezero-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[[bin]]
name = "edgezero-node"
path = "src/main.rs"

[dependencies]
edgezero-core.workspace = true

[lints]
workspace = true
