[workspace]
members = [
  "crates/ezc_core",
  "crates/ezc_cli",
  "crates/ezc_parser",
  "crates/ezc_parser_spike",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/edgezero/edgezero"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
