[package]
name = "presolve-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
wasm = []

[dependencies]
ezc_parser = { package = "presolve-parser", path = "../ezc_parser" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
