contract_version = "0.1"

[application]
name = "hello-edgezero"
version = "0.0.1"
description = "The first EdgeZero WebAssembly Component"

[resources]
memory_mib = 64
cpu_millis = 100

[network]
outbound = "deny"
