contract_version = "0.1"

[application]
name = "hello-presolve"
version = "0.0.1"
description = "The first Presolve WebAssembly Component"

[resources]
memory_mib = 64
cpu_millis = 100

[network]
outbound = "deny"
