[package]
name = "presolve-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[[bin]]
name = "ez"
path = "src/main.rs"

[dependencies]
presolve-core.workspace = true

[lints]
workspace = true
