[package]
name = "presolve-bundle"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
presolve-contract.workspace = true
presolve-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tar = "0.4"

[dev-dependencies]
anyhow.workspace = true

[lints]
workspace = true
